INSERT INTO game (name) VALUES ('Don''t Starve')
,('Outlast')
,('Dead Nation: Apocalypse Edition')
,('Mercenary Kings')
,('Fez')
,('Spelunky')
,('Secert Ponchos')
,('The Swapper')
,('Apotheon')
,('Oddworld: New ''n'' Tasty')
,('Never Alone')
,('Ether One')
,('Hohokum')
,('Super Exploding Zoo')
,('Skulls of the Shogun')
,('Pix the Cat')
,('Styx: Master of Shadows')
,('Entwined')
,('MouseCraft')
,('Lara Croft and the Temple of Osiris')
,('Limbo')
,('Grow Home')
,('Magicka 2')
,('The Walking Dead: Season 2')
,('King''s Quest')
,('Grim Fandango Remastered')
,('Dragon Fin Soup')
,('Helldivers')
,('Super Meat Boy!')
,('Galak-z')
,('Flame Over')
,('Tropico 5')
,('Gone Home: Console Edition')
,('Rebel Galaxy')
,('Pumped BMX +')
,('Invisible, Inc. Console Edition')
,('Hyper Void')
,('Tiny Troopers Joint ops')
,('Color Guardians')
,('Grand Theft Auto: San Andreas')
,('Super Star Wars')
,('Day of the Tentacle Remastered')
,('This War of Mine: The Little Ones')
,('The Swindle')
,('Starwhal')
,('Tearaway Unfolded')
,('Lumo')
,('Curses ''N Chaos')
,('Laser Disco Defenders')
,('Typer:Rider')
,('Assassin''s Creed Freedom Cry')
,('Child of Light')
,('We Are Doomed')
,('Amnesia: Collection')
,('Wolfenstein: The Old Blood')
,('Bound')
,('Dungeon Punks')
,('forma.8')
,('Psycho-Pass Mandatory Happiness')
,('Bombing Busters')
,('Ratchet & Clank')
,('Ratchet & Clank: Rift apart')
,('King Oddball')
,('Trials Fusion')
,('XCOM 2')
,('Horizon Zero Dawn')
,('Call of Duty: Black Ops 3')
,('Space Overlords')
,('Absolver')
,('Extreme Exorcism')
,('Heavy Rain')
,('Here They Lie')
,('God of war 3 Remastered')
,('Rocketbirds 2: Evolution')
,('The Bridge')
,('2064: Read Only Memories')
,('Yakuza Kiwami')
,('Burly Men At Sea')
,('South Park: The Fractured But Whole')
,('SOMA')
,('Iconoclasts')
,('Steep')
,('Portal Knights')
,('Fallen Legion: Flames of Rebellion')
,('Hitman')
,('For Honor')
,('Rogue Aces')
,('Nioh')
,('Overcooked')
,('Sonic Mania')
,('Darksiders 3')
,('The Last of Us Remastered')
,('Doom 2')
,('Doom 3')
,('Lego Worlds')
,('God of War')
,('Just Cause 4')
,('Bioshock 1')
,('Bioshock 2')
,('Final Fantasy 8 Remastered')
,('Dead Cells')
,('Uncharted 4: A Thief''s End')
,('Uncharted: The Lost Legacy')
,('Dirt Rally 2.0')
,('Farming Simulator 19')
,('The LEGO Ninjago Movie Video Game')
,('Call of Duty: WW2')
,('Rise of the Tomb Raider')
,('Erica')
,('Call of Duty: Modern Warfare 2 Campaign Remastered')
,('Xenon Valkyrie+')
,('Link-a-Pix Deluxe')
,('Pic-a-Pix Classic')
,('Pic-a-Pix Classic 2')
,('Pixel Devil and the Broken Cartridge')
,('Pic-a-Pix Pieces 2')
,('Word Sudoku by POWGI')
,('One Word by POWGI')
,('Crossovers by POWGI')
,('Mixups by POWGI')
,('Wordsweeper by POWGI')
,('Word Wheel by POWGI')
,('Tic-Tac-Letters by POWGI')
,('Metagal')
,('One More Dungeon')
,('InkSplosion')
,('Star Wars Episode 1: Racer')
,('Word Maze by POWGI')
,('Crypto by POWGI')
,('Music Racer')
,('Castlevania Requiem: Symphony Of The Night & Rondo Of Blood')
,('Uncharted 3')
,('Hollow Knight')
,('Lara Croft GO')
,('Cat Quest')
,('Road Redemption')
,('Rune Lord')
,('Many Faces')
,('Fill-a-pix: Phil''s Epic Adventure')
,('Bugsnax')
,('Mega Man Legacy Collection 2')
,('Destroy All Humans! 2')
,('GreedFall')
,('Axiom Verge')
,('Cast Of The Seven Godsends - Redux')
,('Riddled Corpses Ex')
,('Super Night Riders')
,('Ninjin - Clash of Carrots')
,('Bloodstained: Curse of the Moon 2')
,('Concrete Genie')
,('Chasm')
,('League of Evil')
,('Super Weekend Mode')
,('Rush Rover')
,('Knightin''+')
,('Reed 2')
,('Knights of Pen and Paper 2 Deluxiest Edition')
,('Next Up Hero')
,('Exit The Gungeon')
,('Super Soccer Blast')
,('JigSaw Abundance')
,('Farpoint')
,('Maquette')
,('Guilty Gear Xrd REV 2')
,('Auto Chess')
,('Geometry Wars 3: Dimensions')
,('Metal Slug XX')
,('Fenix Furia')
,('Monster Hunter: World')
,('Fallout 4')
,('The Last Guardian')
,('Resident Evil 7 biohazard')
,('Thumper')
,('Abzu')
,('Subnautica')
,('Rez Infinite')
,('Borderlands 3')
,('Zero Strain')
,('Robozarro')
,('Oddworld: Soulstorm')
,('Zombie Army 4: Dead War')
,('Contraptions')
,('Stranded deep')
,('Wreckfest')
,('Call of Duty: Modern Warfare')
,('Rogue company')
,('Caladrius Blaze')
,('Operation: Tango')
,('Virtua Fighter 5 Ultimate Showdown')
,('Call of Duty: Black Ops 4')
,('Mobile Suit Gundam Battle Operation 2')
,('Hunter''s Arena: Legends')
,('Plants vs. Zombies: Battle for Neighborville')
,('Tennis World Tour 2')
,('The Witness')
,('Bloodstained: Ritual of the Night')
,('Overcooked! All You Can Eat')
,('Hitman 2')
,('Hell Let Loose')
,('PGA Tour 2K21')
,('First Class Trouble')
,('Kingdoms of Amalur: Re-Reckoning')
,('Lego DC Super-Villains')
,('A Plague Tale: Innocence')
,('Block-a-Pix Deluxe')
,('Jak X: Combat Racing')
,('Torchlight 3')
,('Torchlight 2')
,('Sword Art Online: Fatal Bullet')
,('Tales of Vesperia: Definitive Edition')
,('Superepic')
,('Dirt 5')
,('Deep Rock Galactic')
,('Persona 5 Strikers')
,('Planet Coaster: Console Edition')
,('EA Sports UFC 4')
,('Tiny Tina''s Assault on Dragon Keep: A Wonderlands One-shot adventure')
,('Peggle 2')
,('Ghostrunner')
,('ARK: Survival Evolved')
,('88 heroes')
,('MotoGP 17')
,('MotoGP 18')
,('Hood: Outlaws & Legends')
,('Curse of the Dead Gods')
,('Tribes of Midgard')
,('Fifa 22')
,('Naruto to Boruto: Shinobi Striker')
,('Nickelodeon All-Star Brawl')
,('Arcadegeddon')
,('Crash Bandicoot 4: It''s About Time')
,('Yakuza: Like a Dragon')
,('Little Nightmares')
,('TOEM')
,('Granblue Fantasy: Versus')
,('Teenage Mutant Ninja Turtles: The Cowabunga Collection')
,('Teenage Mutant Ninja Turtles: Shredder''s Revenge')
,('Hot Wheels Unleashed')
,('Injustice 2')
,('Superhot')
,('Heavenly Bodies')
,('Lego Harry Potter Collection')
,('Nioh 2')
,('Mass Effect Legendary Edition')
,('Biomutant')
,('Divine Knockout')
,('Star Wars Jedi: Fallen Order')
,('Fallout 76')
,('Axiom Verge 2')
,('Evil Dead: The Game')
,('Mafia: Definitive Edition')
,('OlliOlli World')
,('Destiny 2')
,('Battlefield 2042')
,('Minecraft Dungeons')
,('Code Vein')
,('Everybody''s Gone To The Rapture')
,('Nova-111')
,('Disgaea 5: Alliance of Vengeance')
,('Mafia III')
,('"Mortal Shell "')
,('WWE 2K Battlegrounds')
,('Jump King')
,('Resident Evil')
,('Vampyr')
,('Borderlands: The Pre-Sequel')
,('Escape Plan')
,('Gunlord X')
,('Scott Pilgrim vs. the World: The Game')
,('Futuridium EP Deluxe')
,('Seum')
,('TorqueL')
,('Super Time Force Ultra')
,('Heroland')
,('Persona 5: Dancing in Starlight')
,('Q.U.B.E: Director''s Cut')
,('Unmechanical Extended')
,('Godfall')
,('Super Blackjack Battle 2 Turbo Edition')
,('Outlast 2')
,('Sparkle 2')
,('Grand Kingdom')
,('Dust: An Elysian Tail')
,('Predator: Hunting Grounds')
,('Azkend 2')
,('Arc of Alchemist')
,('Days Gone')
,('"In Space We Brawl "')
,('Hatoful Boyfriend')
,('Stealth Inc 2: A Game of Clones')
,('Call of Duty: WWII')
,('The Deadly Tower of Monsters')
,('Samurai Warriors 4 Empires')
,('Super Blood Hockey')
,('Detroit: Become Human')
,('Hue')
,('Tony Hawk''s Pro Skater 1 + 2')
,('Neon Abyss')
,('Timber Tennis: Versus')
,('Deus Ex: Mankind Divided')
,('Broken Age')
,('Need for Speed Heat')
,('SteamWorld Dig')
,('Beyond: Two Souls')
,('Don''t Die, Mr. Robot!')
,('Middle-earth: Shadow of War')
,('Meet Your Maker')
,('Sackboy: A Big Adventure')
,('Tails of Iron')
,('Chivalry 2')
,('Descenders')
,('GRID Legends')
,('Super Mario 3D World + Bowser''s Fury')
,('WarioWare: Get It Together!')
,('New Super Mario Bros. U Deluxe')
,('Super Mario 64')
,('Super Mario Galaxy')
,('Mario Tennis Aces')
,('Super Mario Odyssey')
,('51 Worldwide Games')
,('Donkey Kong Country: Tropical Freeze')
,('Super Mario Maker 2');